update format action

diff --git a/.github/workflows/format.yaml b/.github/workflows/format.yaml
--- a/.github/workflows/format.yaml
+++ b/.github/workflows/format.yaml
@@ -3,6 +3,8 @@ name: Format Go code
 on:
   pull_request:
     paths:
+      - "**.go"
+      - go.mod
       - ".github/workflows/format.yml"
   # allow this workflow to be called from other workflows
   workflow_call:
@@ -54,4 +56,5 @@ jobs:
           # push the commit back up to source GitHub repository
           git push
 
-          echo "::warning title=FORMAT-CHANGES::Formatting changes made, please review and merge them"
+          echo "::error title=FORMAT-CHANGES::Formatting changes made, aborting workflow."
+          exit 1
